In [1]:
#a list of employeees salary
salaries = [20000,25000,30000,40000,50000]

In [2]:
import numpy as np
salaries2019 = [20000,25000,30000,40000,50000]

#pass salaries2019to numpy array
np_salaries = np.array(salaries2019)

#output np_salaries
np_salaries

array([20000, 25000, 30000, 40000, 50000])

In [3]:
#use sum() to  sum values in np_salaries
total_salaries = sum(np_salaries)
total_salaries

165000

In [4]:
#find average salaries
average_salaries = np.median(np_salaries)
average_salaries

30000.0

In [5]:
#create a mixed numpy array
#it will be converted to string
np.array(["marv",35000,True])

array(['marv', '35000', 'True'], dtype='<U5')

In [6]:
#a simple list
python_list = [1,2,3]

In [8]:
#numpy array
numpy_array = np.array([1,2,3])

In [10]:
#concatenate the simple list together
python_list + python_list

[1, 2, 3, 1, 2, 3]

In [11]:
numpy_array + numpy_array

array([2, 4, 6])

In [13]:
#create a new list
salaries2019 = [20000,25000,30000,40000,50000]

new_salaries = np.array(salaries2019)
new_salaries

#select an element from the array using its index
new_salaries[1]


25000

In [14]:
#2D NuMpy Arrays
#create np_salaries
np_salaries = np.array([20000,30000,40000,50000])

In [15]:
#ctreate np services
np_service = np.array([1,2,3,4,5,6,7])

In [16]:
#print out type
print(type(np_salaries))
print(type(np_service))


<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [21]:
#combine two lists together sorrounded in square brackets
np_2d_array = np.array([[20000,30000,40000,50000,60000,1345,60005],[1,2,3,4,5,6,7]])
np_2d_array

array([[20000, 30000, 40000, 50000, 60000,  1345, 60005],
       [    1,     2,     3,     4,     5,     6,     7]])

In [22]:
np_2d_array.shape

(2, 7)

In [23]:
np_2d_array[0][2]

40000

In [24]:
np_2d_array[0,2]

40000

In [25]:
total_salaries = sum(np_2d_array[0])
total_salaries

261350